[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "openTEPES"
dist-name = "openTEPES"
author = "IIT-EnergySystemModels"
author-email = "andres.ramos@comillas.edu"
home-page = "https://pascua.iit.comillas.edu/aramos/openTEPES/index.html"
classifiers = [
"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
"Programming Language :: Python :: 3.8","Programming Language :: Python :: 3.9",]
requires-python = ">=3.8"
description-file = "README.rst"
requires = ["pyomo>=5.7.3",
  "matplotlib>=3.3.4",
  "numpy>=1.20.1",
  "pandas>=1.2.3",
  "altair>=4.2.0",
  "psutil>=5.8.0"]

[tool.flit.scripts]
openTEPES_Main = "openTEPES:main"
